### ISSUE TITLE
Full screen mode doesn't work in Chrome. Works in Firefox.

### ISSUE THREAD

**Issue by thenrich2009** [mpetroff/pannellum#299]
I took the API example at https://pannellum.org/documentation/examples/simple-example/ and use it locally on my machine. When I switch to full screen mode. I get the same image in the middle of the screen with the same original size. It doesn't expand to fill the screen. I used Chrome and Canary without extensions and same result.

The same sample works fine in Firefox. 

Any ideas?

**Comment by mpetroff** [comment]
This is a regression I introduced a few days ago in c22ac5d6fe7de2a8178b82bd8dfd09bed717a9d1. I just fixed it in a0b239066d347e3b7a9a0f11c05a4a235dbc155c.

**Comment by nestopia** [comment]
I am still facing a similar issue with the latest version 2.3.2

I am using the javascript references to load the image within a div tag. However when i switch to Fullscreen mode the pano shows up as a thin bar in the  centre of the screen instead of the full screen.

This again happens on chrome and not in firefox.
refer attachment for example.

Please Help

<img width="960" alt="screen shot 2017-02-27 at 4 21 24 pm" src="https://cloud.githubusercontent.com/assets/5682027/23358712/173454c6-fd09-11e6-803c-17ad823df6b9.png">

**Comment by mpetroff** [comment]
Do you have an example page that demonstrates this behavior? I can't be of any help without more information.

**Comment by jogerq** [comment]
Hello,
I have the same problem. You can see it in : http://impulsoyweb.com/desarrollos/vr/ and click "Pantalla Completa" in the menu. That works in firefox, but doesn't work in chrome.

**Comment by mpetroff** [comment]
@jogerq Your issue is because you set `position: absolute` on `#panorama1`. It's unrelated to this (resolved) bug.

**Comment by jogerq** [comment]
Thank you! You are right!

**Comment by olaf100** [comment]
Is there a solution for the problem if i set position: absolute on #panorama?

Is there a workaround?

**Comment by strarsis** [comment]
@olaf100: The easiest solution comes to mind being changing `position` from `absolute` to `static` in case of full screen event and back when full screen is left.
