### ISSUE TITLE
Doubleclicking a scene change hotspot will freeze rendering

### ISSUE THREAD

**Issue by vankessel** [mpetroff/pannellum#303]
As the title says, doubleclicking a scene change hotspot will cause the rendering to bug out. The hotspots work like normal and move around when dragging the panorama, but the panorama will remain frozen in place. Changing scenes will cause a fadeout, but then remain frozen again. Tested in Firefox.

**Comment by mpetroff** [comment]
Thanks. I just fixed it.

**Comment by sandeep-chinthoju** [comment]
Hi, 
I'm currently using the latest version which is 2.3.2 in Chrome. I still have the same issue mentioned above.
Description : When double clicked or clicked multiple times on the hotspot, hotspots on the image are moved to a different location and you can no longer navigate to the next image.

**Comment by mpetroff** [comment]
This was fixed on November 23. Version 2.3.2 was released on November 20. Obviously, the fix is not in 2.3.2.

**Comment by sandeep-chinthoju** [comment]
@mpetroff, appreciate your response.
When can we expect the next release?

**Comment by mpetroff** [comment]
When it's ready.
