### ISSUE TITLE
small visual glitch with inertia

### ISSUE THREAD

**Issue by danielnaber** [mpetroff/pannellum#35]
* click left mouse button
* move mouse quite fast
* before releasing the button, wait  a second or two
* the image now moves a bit, it would be more natural if it didn't

**Comment by mpetroff** [comment]
It should be fixed now. The `mousemove` event, which was updating the speed, stops firing when the mouse stops moving, so abrupt stops left a large speed. I'm now clearing the speed when the mouse button is released if `mousemove` hasn't fired recently.

**Comment by danielnaber** [comment]
I still have the impression that Flash-based player like http://openpano.org/demo/ are a bit smoother when panning the view, but this is fixed. Thanks!
