### ISSUE TITLE
Issue with array reference

### ISSUE THREAD

**Issue by ajorquera** [mpetroff/pannellum#495]
https://github.com/mpetroff/pannellum/blob/793918c2556aca9a19ef7c5aa672a01ec67430ef/src/js/pannellum.js#L1753

There a bug in this area which is breaking the viewer. I fixed the issue by resetting the array after the for loop

hs.length = 0;

**Comment by mpetroff** [comment]
You're going to have to be a bit more specific than "breaking the viewer."

**Comment by mpetroff** [comment]
I fixed the bug I saw in that function in f0a7fcf02c8851124fad7c437e23f51b1e8a3f40, but without knowing what issue you're referring to, I don't know whether or not I fixed it.

**Comment by ajorquera** [comment]
The changes you did, doesnt fix the issue. Basically on the loop

     while(current.parentNode != renderContainer) {
                current = current.parentNode;
     }

In some point, current gets assign null, which breaks when it tries to access current.parentNode. 

Also, I notice, when you debug the code the array hs has duplicated elements inside. My solution was just to reset the array at the end of the function with 

    hs.length = 0;

Hope that helps.

**Comment by mpetroff** [comment]
Do you have an example that displays this behavior? I can't reproduce it.

**Comment by ajorquera** [comment]
Sorry, I don't have an example I can show.  I had a virtual tour with multiple panoramas and after changing views several times,, back and forward, the error happens and breaks the viewer.
